import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { X } from 'lucide-react';

export const MenuDrawer = ({ isOpen, onClose }) => {
  const menuItems = [
      { path: '/', label: 'Home', number: '01' },
          { path: '/collection', label: 'Shop', number: '02' },
              { path: '/about', label: 'About', number: '03' },
                  { path: '/journal', label: 'Journal', number: '04' },
                      { path: '/contact', label: 'Contact', number: '05' },
                        ];

                          useEffect(() => {
                              if (isOpen) document.body.style.overflow = 'hidden';
                                  else document.body.style.overflow = '';
                                      return () => { document.body.style.overflow = ''; };
                                        }, [isOpen]);

                                          return (
                                              <AnimatePresence>
                                                    {isOpen && (
                                                            <motion.div
                                                                      initial={{ opacity: 0 }}
                                                                                animate={{ opacity: 1 }}
                                                                                          exit={{ opacity: 0 }}
                                                                                                    transition={{ duration: 0.4 }}
                                                                                                              className="fixed inset-0 z-[100] bg-black flex flex-col"
                                                                                                                      >
                                                                                                                                {/* Top Bar */}
                                                                                                                                          <div className="flex items-center justify-between px-6 md:px-12 py-6">
                                                                                                                                                      <span className="text-[9px] font-mono uppercase tracking-[0.5em] text-white/30">
                                                                                                                                                                    Navigation
                                                                                                                                                                                </span>
                                                                                                                                                                                            <Link to="/" onClick={onClose}>
                                                                                                                                                                                                          <h1 style={{fontFamily: "'Cormorant Garamond', serif"}}
                                                                                                                                                                                                                          className="text-2xl font-light tracking-[0.3em] uppercase text-white">
                                                                                                                                                                                                                                          NEVO
                                                                                                                                                                                                                                                        </h1>
                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                <button onClick={onClose} className="text-white hover:text-red-600 transition-colors">
                                                                                                                                                                                                                                                                                              <X className="w-5 h-5" strokeWidth={1} />
                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                              {/* Divider */}
                                                                                                                                                                                                                                                                                                                                        <div className="h-[1px] bg-white/5 mx-6 md:mx-12" />

                                                                                                                                                                                                                                                                                                                                                  {/* Menu Links */}
                                                                                                                                                                                                                                                                                                                                                            <nav className="flex-1 flex flex-col justify-center px-6 md:px-12">
                                                                                                                                                                                                                                                                                                                                                                        {menuItems.map((item, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                      <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                      key={item.path}
                                                                                                                                                                                                                                                                                                                                                                                                                      initial={{ opacity: 0, y: 30 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                      animate={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      exit={{ opacity: 0, y: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transition={{ delay: idx * 0.08, duration: 0.4 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      to={item.path}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={onClose}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="group flex items-center gap-6 py-5 border-b border-white/5 hover:border-white/20 transition-all duration-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-[9px] font-mono text-white/20 group-hover:text-red-600 transition-colors w-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {item.number}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{fontFamily: "'Cormorant Garamond', serif"}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="text-4xl md:text-6xl font-light uppercase tracking-wide text-white group-hover:text-red-600 transition-all duration-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {item.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        initial={{ opacity: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    animate={{ opacity: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                transition={{ delay: 0.5 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="px-6 md:px-12 py-8 border-t border-white/5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex flex-col md:flex-row justify-between gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex gap-6 text-[9px] font-mono uppercase tracking-widest text-white/30">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="#" className="hover:text-red-600 transition-colors">Instagram</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="opacity-20">/</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="#" className="hover:text-red-600 transition-colors">Discord</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="opacity-20">/</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="#" className="hover:text-red-600 transition-colors">Twitter</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-[9px] font-mono uppercase tracking-widest text-white/20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            © 2026 NEVO Studio
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </AnimatePresence>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };